#############################################################################
# Makefile for building: bludiste
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun May 11 21:15:06 2014
# Project:  src/bludiste.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile src/bludiste.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -Isrc -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -Isrc -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lboost_system -pthread -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/server.cpp \
		src/client.cpp \
		src/character.cpp \
		src/square.cpp \
		src/board.cpp \
		src/serverwindow.cpp \
		src/clientwindow.cpp \
		src/connectdialog.cpp \
		src/controller.cpp moc_mainwindow.cpp \
		moc_serverwindow.cpp \
		moc_clientwindow.cpp \
		moc_connectdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		server.o \
		client.o \
		character.o \
		square.o \
		board.o \
		serverwindow.o \
		clientwindow.o \
		connectdialog.o \
		controller.o \
		moc_mainwindow.o \
		moc_serverwindow.o \
		moc_clientwindow.o \
		moc_connectdialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		src/bludiste.pro
QMAKE_TARGET  = bludiste2014
DESTDIR       = 
TARGET        = bludiste2014

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_serverwindow.h ui_clientwindow.h ui_connectdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: src/bludiste.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile src/bludiste.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile src/bludiste.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/bludiste1.0.0 || $(MKDIR) .tmp/bludiste1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/bludiste1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/server.h src/client.h src/character.h src/square.h src/board.h src/serverwindow.h src/clientwindow.h src/connectdialog.h src/controller.h .tmp/bludiste1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/server.cpp src/client.cpp src/character.cpp src/square.cpp src/board.cpp src/serverwindow.cpp src/clientwindow.cpp src/connectdialog.cpp src/controller.cpp .tmp/bludiste1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui src/serverwindow.ui src/clientwindow.ui src/connectdialog.ui .tmp/bludiste1.0.0/ && (cd `dirname .tmp/bludiste1.0.0` && $(TAR) bludiste1.0.0.tar bludiste1.0.0 && $(COMPRESS) bludiste1.0.0.tar) && $(MOVE) `dirname .tmp/bludiste1.0.0`/bludiste1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bludiste1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) -r ./doc/html
	-$(DEL_FILE) -r ./doc/latex
	rm -f $(TARGET)


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_serverwindow.cpp moc_clientwindow.cpp moc_connectdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_serverwindow.cpp moc_clientwindow.cpp moc_connectdialog.cpp
moc_mainwindow.cpp: src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

moc_serverwindow.cpp: src/serverwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/serverwindow.h -o moc_serverwindow.cpp

moc_clientwindow.cpp: src/client.h \
		src/clientwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/clientwindow.h -o moc_clientwindow.cpp

moc_connectdialog.cpp: src/connectdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/connectdialog.h -o moc_connectdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_serverwindow.h ui_clientwindow.h ui_connectdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_serverwindow.h ui_clientwindow.h ui_connectdialog.h
ui_mainwindow.h: src/mainwindow.ui
	/usr/bin/uic-qt4 src/mainwindow.ui -o ui_mainwindow.h

ui_serverwindow.h: src/serverwindow.ui
	/usr/bin/uic-qt4 src/serverwindow.ui -o ui_serverwindow.h

ui_clientwindow.h: src/clientwindow.ui
	/usr/bin/uic-qt4 src/clientwindow.ui -o ui_clientwindow.h

ui_connectdialog.h: src/connectdialog.ui
	/usr/bin/uic-qt4 src/connectdialog.ui -o ui_connectdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/controller.h \
		src/board.h \
		src/square.h \
		src/character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		ui_mainwindow.h \
		src/serverwindow.h \
		src/clientwindow.h \
		src/client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

server.o: src/server.cpp src/server.h \
		src/controller.h \
		src/board.h \
		src/square.h \
		src/character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o src/server.cpp

client.o: src/client.cpp src/client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o src/client.cpp

character.o: src/character.cpp src/character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character.o src/character.cpp

square.o: src/square.cpp src/square.h \
		src/character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o square.o src/square.cpp

board.o: src/board.cpp src/board.h \
		src/square.h \
		src/character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o board.o src/board.cpp

serverwindow.o: src/serverwindow.cpp src/serverwindow.h \
		ui_serverwindow.h \
		src/server.h \
		src/controller.h \
		src/board.h \
		src/square.h \
		src/character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serverwindow.o src/serverwindow.cpp

clientwindow.o: src/clientwindow.cpp src/clientwindow.h \
		src/client.h \
		ui_clientwindow.h \
		src/connectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientwindow.o src/clientwindow.cpp

connectdialog.o: src/connectdialog.cpp src/connectdialog.h \
		ui_connectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectdialog.o src/connectdialog.cpp

controller.o: src/controller.cpp src/controller.h \
		src/board.h \
		src/square.h \
		src/character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o src/controller.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_serverwindow.o: moc_serverwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serverwindow.o moc_serverwindow.cpp

moc_clientwindow.o: moc_clientwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientwindow.o moc_clientwindow.cpp

moc_connectdialog.o: moc_connectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectdialog.o moc_connectdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

doxygen:
	doxygen doc/config

run:
	./bludiste2014

FORCE:

